2021-07-11 15:41:07,384 ERROR: Exception on / [GET] [in /Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/davidjohnson/github.com/DevLog/app/routes.py", line 43, in index
    return render_template(
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/davidjohnson/github.com/DevLog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/davidjohnson/github.com/DevLog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/Users/davidjohnson/github.com/DevLog/app/templates/base.html", line 22, in block 'navbar'
    <li><a href="{{ url_for('index') }}">{{ _('Home') }}</a></li>
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: '_' is undefined
2021-07-11 15:44:48,843 INFO: Microblog startup [in /Users/davidjohnson/github.com/DevLog/app/__init__.py:50]
2021-07-11 15:44:53,185 ERROR: Exception on / [GET] [in /Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/davidjohnson/github.com/DevLog/app/routes.py", line 43, in index
    return render_template(
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/davidjohnson/github.com/DevLog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/davidjohnson/github.com/DevLog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/Users/davidjohnson/github.com/DevLog/app/templates/base.html", line 37, in block 'navbar'
    <a href="{{ url_for('messages') }}">Message
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/davidjohnson/.local/share/virtualenvs/DevLog-xf7EW5ut/lib/python3.9/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'messages'. Did you mean 'register' instead?
2021-07-11 15:45:33,382 INFO: Microblog startup [in /Users/davidjohnson/github.com/DevLog/app/__init__.py:50]
